vcenter input/processor and grafana output for vc input
devopsext/events pull request #11
Opened 2022-06-22 08:50 UTC by askripe

grafana output for vc input updated
add vc input
add vcenter processore
remove vcenter package move filtering logic into template
errors fixing for telegram output
some error handling
rewrite vcenter processor
add sample events from vcenter
add rate limiter
add debug print for spaning errors
add vcenter events output into grafana templates
finalize telegram templates
grafana will add annotation instead of region annotation
update go.mod/go.sum

typos and warnings

implement some events

2022-07-05 10:53 UTC, XCiber requested changes

2022-07-05 10:53 UTC, XCiber commented on output/grafana.go
> +		err = g.grafanaEventer.Interval(message, attributes, event.Time, event.Time)
return At for now pls

2022-07-08 07:19 UTC, askripe commented on processor/vcenter.go
> +		//
fixed

2022-07-08 07:20 UTC, askripe commented on grafana.attributes
> +{{- define "vcenter"}}
fixed

2022-07-08 07:20 UTC, askripe commented on grafana.message
> +{{- define "vcenter"}}
fixed

2022-07-12 12:55 UTC, XCiber approved these changes

2022-07-12 12:58 UTC, merged